### PR TITLE
Assign 4

### PR DESCRIPTION
**Pull request by IM-Mukesh**
as4-1
as4-2

### CODE REVIEW

**Review by rijav1001 — COMMENTED** [review]
nice and neat!

**Comment by IM-Mukesh** [comment]
Thanks, Rijav for the Review

**Comment by saikiransathpadi** [comment]
correct and looking good
data didn't render and you haven't called the post component in index.js

**Comment by IM-Mukesh** [comment]
@saikiransathpadi 
It is rendering for me. I don't what is the issue please check once again

**Pull request merged**
